[package]
name = "swiss_qrust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
qrcode = "0.14.1"
regex = "1.12.2"
svg = "0.18.0"
text = "0.0.4"
once_cell = "1.21.3"
bincode = "1.3.3"
serde =  { version = "1.0.228", features = ["derive"]}
thiserror = "2.0.18"


[build-dependencies]
serde =  { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
